create table hero (

  hero_id int AUTO_INCREMENT not null,
  game_id int not null,
  player_name varchar(50) not null,
  hero_name varchar(50) not null,
  level int not null,
  class_name varchar(50) not null,
  xp int not null,
  ap int not null,
  base_strength int not null,
  base_dexterity int not null,
  base_speed int not null,
  base_endurance int not null,
  base_spirit int not null,
  base_intelligence int not null,
  base_willpower int not null,
  base_charisma int not null,
  base_hp int not null,
  base_sp int not null,
  bonus_strength int not null,
  bonus_dexterity int not null,
  bonus_speed int not null,
  bonus_endurance int not null,
  bonus_spirit int not null,
  bonus_intelligence int not null,
  bonus_willpower int not null,
  bonus_charisma int not null,
  bonus_hp int not null,
  bonus_sp int not null,
  current_hp int not null,
  current_sp int not null,

  primary key(hero_id)
);